##teamcity[testSuiteStarted name='TestFx.MSpec.Tests']
##teamcity[testSuiteStarted name='Int32, when calling']
##teamcity[testStarted name='asserts' captureStandardOutput='false']
##teamcity[testFinished name='asserts' duration='xx']
##teamcity[testSuiteFinished name='Int32, when calling']
##teamcity[testSuiteStarted name='Int32, when actioning']
##teamcity[testStarted name='asserts' captureStandardOutput='false']
##teamcity[testFinished name='asserts' duration='xx']
##teamcity[testSuiteFinished name='Int32, when actioning']
##teamcity[testSuiteStarted name='Int32 is great, when adding']
##teamcity[testStarted name='returns three' captureStandardOutput='false']
##teamcity[testFinished name='returns three' duration='xx']
##teamcity[testStarted name='returns four' captureStandardOutput='false']
##teamcity[testFailed name='returns four' message='AssertionException' details='Operations:|r|nFAILED  returns four (AssertionException)|r|n|r|n|r|nNUnit.Framework.AssertionException:|r|nExpected value to be 4, but found 3.|r|n   at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\Shared\Execution\LateBoundTestFramework.cs:line 31|r|n   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42|r|n   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25|r|n   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[|] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197|r|n   at FluentAssertions.Numeric.NumericAssertions`1.Be(T expected, String because, Object[|] reasonArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Numeric\NumericAssertions.cs:line 44|r|n--- End of stack trace from previous location where exception was thrown ---|r|n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()|r|n']
##teamcity[testFinished name='returns four' duration='xx']
##teamcity[testSuiteFinished name='Int32 is great, when adding']
##teamcity[testSuiteStarted name='Foo, when subject text only']
##teamcity[testStarted name='dummy' captureStandardOutput='false']
##teamcity[testFinished name='dummy' duration='xx']
##teamcity[testSuiteFinished name='Foo, when subject text only']
##teamcity[testSuiteStarted name='Int32, when subject type only']
##teamcity[testStarted name='dummy' captureStandardOutput='false']
##teamcity[testFinished name='dummy' duration='xx']
##teamcity[testSuiteFinished name='Int32, when subject type only']
##teamcity[testSuiteStarted name='Int32, when actioning']
##teamcity[testFailed name='Int32, when actioning' message='Exception' details='Operations:|r|n        Establish outer_context_base|r|n        Establish outer_context|r|nFAILED  Establish base_context_base (Exception)|r|n.. InnerOperations ..|r|n        Cleanup outer_context|r|n        Cleanup outer_context_base|r|n|r|n|r|nSystem.Exception:|r|nException of type |'System.Exception|' was thrown.|r|n--- End of stack trace from previous location where exception was thrown ---|r|n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()|r|n']
##teamcity[testSuiteFinished name='Int32, when actioning']
##teamcity[testSuiteStarted name='Int32, when inconclusive']
##teamcity[testStarted name='is inconclusive' captureStandardOutput='false']
##teamcity[testIgnored name='is inconclusive' message='']
##teamcity[testSuiteFinished name='Int32, when inconclusive']
##teamcity[testSuiteFinished name='TestFx.MSpec.Tests']
